version: "3.8"
services:
  chrome:
    build:
      context: ./node/
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - START_XVFB=false
      - SCREEN_DEPTH=24
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=1024
    restart: "no"

  selenium-hub:
    build:
      context: ./hub/
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: "no"